version: '3.7'

networks:
  internal:

services:
  web:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: chinook-poc-ui-master
    
    networks:
      - internal
    ports:
      - "5000:5000"
